# see docs at https://docs.haskellstack.org/en/stable/yaml_configuration/
name:                Aetherling
version:             0.1.0.0
github:              "David-Durst/Aetherling/theory/AetherlingSTIR"
license:             BSD3
author:              "David Durst"
maintainer:          "davidbdurst@gmail.com"
copyright:           "2018 David Durst"

extra-source-files:
- protoAetherling/**/*.proto

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/David-Durst/Aetherling/theory/AetherlingSTIR#readme>

dependencies:
- base
- finite-typelits 
- vector-sized
- ghc-typelits-extra
- ghc-typelits-natnormalise
- ghc-typelits-knownnat
- ghc-typelits-natnormalise
- singletons
- split
- type-iso
- lens
- reflection
- mtl
- containers
- reflection
- util
- monad-memo
- arithmoi
- sbv
- time
- temporary
- process
- filepath
- directory
- random
- random-shuffle
- safe
- filepath
- timeit
- deepseq
- array
- massiv
- text
- proto-lens
- microlens
- lens-family
- bytestring
- vector

ghc-options:
- -O2
- -fconstraint-solver-iterations=0
- -fwarn-incomplete-patterns 
- -fplugin GHC.TypeLits.KnownNat.Solver
- -fplugin GHC.TypeLits.Extra.Solver
- -fplugin GHC.TypeLits.Normalise
# - -fbreak-on-exception
    #- -Wall - comeback to this, too many warnings right now to handle
    #- -fplugin GHC.TypeLits.KnownNat.Solver

custom-setup:
  dependencies:
    - base
    - Cabal
    - proto-lens-setup

build-tools: proto-lens-protoc:proto-lens-protoc

library:
  dependencies:
  - base
  - proto-lens-runtime
  source-dirs: src/Core
  default-extensions:
    - DataKinds
    - TypeOperators
    - TypeFamilies
    - FlexibleContexts
    - FlexibleInstances
    - ScopedTypeVariables
    - TypeApplications
    - TypeSynonymInstances
    - PolyKinds
    - LiberalTypeSynonyms
    - UndecidableInstances
    - MultiParamTypeClasses
    - AllowAmbiguousTypes
    - PartialTypeSignatures
    - ExistentialQuantification
    - DeriveFoldable
    - DeriveTraversable
    - GADTs
    - ConstraintKinds
    - Rank2Types
    - InstanceSigs
    - BangPatterns
    - DeriveGeneric
    - DeriveAnyClass
    - OverloadedStrings
  other-modules:
    - Proto.Spacetime
    - Proto.Spacetime_Fields
    - Proto.Sequence
    - Proto.Sequence_Fields

#executables:
#  Aetherling-AppTest-exe:
#    main:                Main.hs
#    source-dirs:
#    - src/AppMains/AppTest/
#    ghc-options:
#    - -fprof-auto
#    - -threaded
#    - -with-rtsopts=-N
#    dependencies:
#    - Aetherling
#    default-extensions:
#      - DataKinds
#      - TypeOperators
#      - TypeFamilies
#      - FlexibleContexts
#      - FlexibleInstances
#      - ScopedTypeVariables
#      - TypeApplications
#      - TypeSynonymInstances
#      - PolyKinds
#      - LiberalTypeSynonyms
#      - UndecidableInstances
#      - MultiParamTypeClasses
#      - AllowAmbiguousTypes
#      - PartialTypeSignatures
#      - ExistentialQuantification
#      - DeriveFoldable
#      - DeriveTraversable
#      - GADTs
#      - ConstraintKinds
#      - Rank2Types
#      - InstanceSigs
#  Aetherling-Blur-exe:
#    main:                Main.hs
#    source-dirs:
#    - src/Apps/
#    - src/AppMains/Blur/
#    ghc-options:
#    - -rtsopts
#    - -with-rtsopts=-N
#    dependencies:
#    - Aetherling
#    - stb-image-redux
#    - vector
#    default-extensions:
#      - DataKinds
#      - TypeOperators
#      - TypeFamilies
#      - FlexibleContexts
#      - FlexibleInstances
#      - ScopedTypeVariables
#      - TypeApplications
#      - TypeSynonymInstances
#      - PolyKinds
#      - LiberalTypeSynonyms
#      - UndecidableInstances
#      - MultiParamTypeClasses
#      - AllowAmbiguousTypes
#      - PartialTypeSignatures
#      - ExistentialQuantification
#      - DeriveFoldable
#      - DeriveTraversable
#      - GADTs
#      - ConstraintKinds
#      - Rank2Types
#      - InstanceSigs

tests:
  Aetherling-Tests:
    main:                Test_Main.hs
    source-dirs:
    - test/ 
    ghc-options:
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - Aetherling
    - tasty 
    - tasty-hunit 
    default-extensions:
      - DataKinds
      - TypeOperators
      - TypeFamilies
      - FlexibleContexts
      - FlexibleInstances
      - ScopedTypeVariables
      - TypeApplications
      - TypeSynonymInstances
      - PolyKinds
      - LiberalTypeSynonyms
      - UndecidableInstances
      - MultiParamTypeClasses
      - AllowAmbiguousTypes
      - PartialTypeSignatures
      - ExistentialQuantification
      - DeriveFoldable
      - DeriveTraversable
      - GADTs
      - ConstraintKinds
      - Rank2Types
      - InstanceSigs
