# see docs at https://docs.haskellstack.org/en/stable/yaml_configuration/
name:                Aetherling
version:             0.1.0.0
github:              "David-Durst/Aetherling/theory/AetherlingSTIR"
license:             BSD3
author:              "David Durst"
maintainer:          "davidbdurst@gmail.com"
copyright:           "2018 David Durst"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/David-Durst/Aetherling/theory/AetherlingSTIR#readme>

dependencies:
- base
- finite-typelits 
- vector-sized
- ghc-typelits-extra
- ghc-typelits-natnormalise
- ghc-typelits-knownnat
- ghc-typelits-natnormalise
- singletons
- split
- type-iso
- lens
- reflection
- mtl
- containers
- reflection

ghc-options:
- -fwarn-incomplete-patterns 
- -fplugin GHC.TypeLits.KnownNat.Solver
- -fplugin GHC.TypeLits.Extra.Solver
- -fplugin GHC.TypeLits.Normalise
    #- -Wall - comeback to this, too many warnings right now to handle
    #- -fplugin GHC.TypeLits.KnownNat.Solver

library:
  source-dirs: src/Core
  default-extensions:
    - DataKinds
    - TypeOperators
    - TypeFamilies
    - FlexibleContexts
    - FlexibleInstances
    - ScopedTypeVariables
    - TypeApplications
    - TypeSynonymInstances
    - PolyKinds
    - LiberalTypeSynonyms
    - UndecidableInstances
    - MultiParamTypeClasses
    - AllowAmbiguousTypes
    - PartialTypeSignatures
    - ExistentialQuantification
    - DatatypeContexts
    - DeriveFoldable
    - DeriveTraversable
    - GADTs
    - ConstraintKinds
    - Rank2Types
    - InstanceSigs
