-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2017.2
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity linebuffer_2 is
port (
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    in_stream_V_value_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    in_stream_V_value_V_empty_n : IN STD_LOGIC;
    in_stream_V_value_V_read : OUT STD_LOGIC;
    out_stream_V_value_V_din : OUT STD_LOGIC_VECTOR (127 downto 0);
    out_stream_V_value_V_full_n : IN STD_LOGIC;
    out_stream_V_value_V_write : OUT STD_LOGIC;
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC );
end;


architecture behav of linebuffer_2 is 
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv128_lc_1 : STD_LOGIC_VECTOR (127 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";

    signal real_start : STD_LOGIC;
    signal real_start_status_reg : STD_LOGIC := '0';
    signal internal_ap_ready : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal start_control_reg : STD_LOGIC := '0';
    signal call_1_U0_in_stream_V_value_V_read : STD_LOGIC;
    signal call_1_U0_out_stream_V_value_V_din : STD_LOGIC_VECTOR (127 downto 0);
    signal call_1_U0_out_stream_V_value_V_write : STD_LOGIC;
    signal call_1_U0_ap_done : STD_LOGIC;
    signal call_1_U0_ap_start : STD_LOGIC;
    signal call_1_U0_ap_ready : STD_LOGIC;
    signal call_1_U0_ap_idle : STD_LOGIC;
    signal call_1_U0_ap_continue : STD_LOGIC;
    signal ap_sync_continue : STD_LOGIC;
    signal ap_sync_done : STD_LOGIC;
    signal ap_sync_ready : STD_LOGIC;
    signal call_1_U0_start_full_n : STD_LOGIC;
    signal call_1_U0_start_write : STD_LOGIC;

    component call_1 IS
    port (
        in_stream_V_value_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        in_stream_V_value_V_empty_n : IN STD_LOGIC;
        in_stream_V_value_V_read : OUT STD_LOGIC;
        out_stream_V_value_V_din : OUT STD_LOGIC_VECTOR (127 downto 0);
        out_stream_V_value_V_full_n : IN STD_LOGIC;
        out_stream_V_value_V_write : OUT STD_LOGIC;
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;



begin
    call_1_U0 : component call_1
    port map (
        in_stream_V_value_V_dout => in_stream_V_value_V_dout,
        in_stream_V_value_V_empty_n => in_stream_V_value_V_empty_n,
        in_stream_V_value_V_read => call_1_U0_in_stream_V_value_V_read,
        out_stream_V_value_V_din => call_1_U0_out_stream_V_value_V_din,
        out_stream_V_value_V_full_n => out_stream_V_value_V_full_n,
        out_stream_V_value_V_write => call_1_U0_out_stream_V_value_V_write,
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_done => call_1_U0_ap_done,
        ap_start => call_1_U0_ap_start,
        ap_ready => call_1_U0_ap_ready,
        ap_idle => call_1_U0_ap_idle,
        ap_continue => call_1_U0_ap_continue);





    real_start_status_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                real_start_status_reg <= ap_const_logic_0;
            else
                if ((start_full_n = ap_const_logic_1)) then 
                    real_start_status_reg <= ap_const_logic_0;
                elsif (((start_full_n = ap_const_logic_0) and (internal_ap_ready = ap_const_logic_1))) then 
                    real_start_status_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    start_control_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_control_reg <= ap_const_logic_0;
            else
                if (((real_start = ap_const_logic_1) and ((internal_ap_ready = ap_const_logic_1) or (ap_const_logic_0 = start_once_reg)))) then 
                    start_control_reg <= ap_const_logic_1;
                elsif ((ap_const_logic_1 = start_control_reg)) then 
                    start_control_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if ((real_start = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((ap_start = ap_const_logic_0)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    ap_done <= call_1_U0_ap_done;
    ap_idle <= call_1_U0_ap_idle;
    ap_ready <= internal_ap_ready;
    ap_sync_continue <= ap_continue;
    ap_sync_done <= call_1_U0_ap_done;
    ap_sync_ready <= call_1_U0_ap_ready;
    call_1_U0_ap_continue <= ap_continue;
    call_1_U0_ap_start <= real_start;
    call_1_U0_start_full_n <= ap_const_logic_0;
    call_1_U0_start_write <= ap_const_logic_0;
    in_stream_V_value_V_read <= call_1_U0_in_stream_V_value_V_read;
    internal_ap_ready <= ap_sync_ready;
    out_stream_V_value_V_din <= call_1_U0_out_stream_V_value_V_din;
    out_stream_V_value_V_write <= call_1_U0_out_stream_V_value_V_write;

    real_start_assign_proc : process(ap_start, real_start_status_reg)
    begin
        if ((real_start_status_reg = ap_const_logic_1)) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_out <= real_start;
    start_write <= (ap_start and start_control_reg);
end behav;
