// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "call_Loop_LB2D_buf_p_1.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic call_Loop_LB2D_buf_p_1::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic call_Loop_LB2D_buf_p_1::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<4> call_Loop_LB2D_buf_p_1::ap_ST_fsm_state1 = "1";
const sc_lv<4> call_Loop_LB2D_buf_p_1::ap_ST_fsm_state2 = "10";
const sc_lv<4> call_Loop_LB2D_buf_p_1::ap_ST_fsm_pp0_stage0 = "100";
const sc_lv<4> call_Loop_LB2D_buf_p_1::ap_ST_fsm_state6 = "1000";
const bool call_Loop_LB2D_buf_p_1::ap_const_boolean_1 = true;
const sc_lv<32> call_Loop_LB2D_buf_p_1::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> call_Loop_LB2D_buf_p_1::ap_const_lv32_2 = "10";
const bool call_Loop_LB2D_buf_p_1::ap_const_boolean_0 = false;
const sc_lv<1> call_Loop_LB2D_buf_p_1::ap_const_lv1_0 = "0";
const sc_lv<32> call_Loop_LB2D_buf_p_1::ap_const_lv32_1 = "1";
const sc_lv<1> call_Loop_LB2D_buf_p_1::ap_const_lv1_1 = "1";
const sc_lv<11> call_Loop_LB2D_buf_p_1::ap_const_lv11_0 = "00000000000";
const sc_lv<32> call_Loop_LB2D_buf_p_1::ap_const_lv32_3 = "11";
const sc_lv<11> call_Loop_LB2D_buf_p_1::ap_const_lv11_436 = "10000110110";
const sc_lv<11> call_Loop_LB2D_buf_p_1::ap_const_lv11_1 = "1";
const sc_lv<11> call_Loop_LB2D_buf_p_1::ap_const_lv11_77E = "11101111110";

call_Loop_LB2D_buf_p_1::call_Loop_LB2D_buf_p_1(sc_module_name name) : sc_module(name), mVcdFile(0) {
    buffer_0_value_V_U = new call_Loop_LB2D_bufYi("buffer_0_value_V_U");
    buffer_0_value_V_U->clk(ap_clk);
    buffer_0_value_V_U->reset(ap_rst);
    buffer_0_value_V_U->address0(buffer_0_value_V_address0);
    buffer_0_value_V_U->ce0(buffer_0_value_V_ce0);
    buffer_0_value_V_U->q0(buffer_0_value_V_q0);
    buffer_0_value_V_U->address1(buffer_0_value_V_address1);
    buffer_0_value_V_U->ce1(buffer_0_value_V_ce1);
    buffer_0_value_V_U->we1(buffer_0_value_V_we1);
    buffer_0_value_V_U->d1(tmp_value_V_3_reg_194);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0);
    sensitive << ( ap_block_pp0_stage0_flag00011011 );

    SC_METHOD(thread_ap_block_pp0_stage0_flag00000000);

    SC_METHOD(thread_ap_block_pp0_stage0_flag00001001);
    sensitive << ( in_stream_V_value_V_empty_n );
    sensitive << ( slice_stream_V_value_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( tmp_s_reg_171 );

    SC_METHOD(thread_ap_block_pp0_stage0_flag00011001);
    sensitive << ( in_stream_V_value_V_empty_n );
    sensitive << ( slice_stream_V_value_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( tmp_s_reg_171 );

    SC_METHOD(thread_ap_block_pp0_stage0_flag00011011);
    sensitive << ( in_stream_V_value_V_empty_n );
    sensitive << ( slice_stream_V_value_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( tmp_s_reg_171 );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter1);
    sensitive << ( in_stream_V_value_V_empty_n );

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter2);
    sensitive << ( slice_stream_V_value_V_full_n );
    sensitive << ( tmp_s_reg_171 );

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state3);
    sensitive << ( tmp_1_fu_138_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( tmp_fu_120_p2 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_enable_operation_30);
    sensitive << ( ap_predicate_op30_load_state3 );

    SC_METHOD(thread_ap_enable_operation_32);
    sensitive << ( tmp_s_reg_171 );

    SC_METHOD(thread_ap_enable_operation_40);
    sensitive << ( ap_reg_pp0_iter1_tmp_1_reg_175 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_enable_state3_pp0_iter0_stage0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_ap_enable_state4_pp0_iter1_stage0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_ap_enable_state5_pp0_iter2_stage0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( real_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_ap_predicate_op30_load_state3);
    sensitive << ( tmp_s_reg_171 );
    sensitive << ( tmp_1_fu_138_p2 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( internal_ap_ready );

    SC_METHOD(thread_buffer_0_value_V_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_flag00000000 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( col_cast_fu_150_p1 );

    SC_METHOD(thread_buffer_0_value_V_address1);
    sensitive << ( ap_block_pp0_stage0_flag00000000 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_reg_pp0_iter1_col_cast_reg_184 );

    SC_METHOD(thread_buffer_0_value_V_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_flag00011001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_buffer_0_value_V_ce1);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0_flag00011001 );

    SC_METHOD(thread_buffer_0_value_V_we1);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0_flag00011001 );
    sensitive << ( ap_reg_pp0_iter1_tmp_1_reg_175 );

    SC_METHOD(thread_col_1_fu_144_p2);
    sensitive << ( col_reg_109 );

    SC_METHOD(thread_col_cast_fu_150_p1);
    sensitive << ( col_reg_109 );

    SC_METHOD(thread_in_stream_V_value_V_blk_n);
    sensitive << ( in_stream_V_value_V_empty_n );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_flag00000000 );

    SC_METHOD(thread_in_stream_V_value_V_read);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_flag00011001 );

    SC_METHOD(thread_internal_ap_ready);
    sensitive << ( tmp_fu_120_p2 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_real_start);
    sensitive << ( ap_start );
    sensitive << ( real_start_status_reg );

    SC_METHOD(thread_row_1_fu_126_p2);
    sensitive << ( row_reg_98 );

    SC_METHOD(thread_slice_stream_V_value_V_blk_n);
    sensitive << ( slice_stream_V_value_V_full_n );
    sensitive << ( ap_block_pp0_stage0_flag00000000 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( tmp_s_reg_171 );

    SC_METHOD(thread_slice_stream_V_value_V_din);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( tmp_s_reg_171 );
    sensitive << ( tmp_value_V_3_reg_194 );
    sensitive << ( p_Val2_s_reg_200 );
    sensitive << ( ap_block_pp0_stage0_flag00001001 );

    SC_METHOD(thread_slice_stream_V_value_V_write);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( tmp_s_reg_171 );
    sensitive << ( ap_block_pp0_stage0_flag00011001 );

    SC_METHOD(thread_start_out);
    sensitive << ( real_start );

    SC_METHOD(thread_start_write);
    sensitive << ( ap_start );
    sensitive << ( start_control_reg );

    SC_METHOD(thread_tmp_1_fu_138_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( col_reg_109 );
    sensitive << ( ap_block_pp0_stage0_flag00011001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_tmp_fu_120_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( row_reg_98 );

    SC_METHOD(thread_tmp_s_fu_132_p2);
    sensitive << ( tmp_fu_120_p2 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( row_reg_98 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( tmp_fu_120_p2 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_1_fu_138_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_flag00011011 );

    real_start_status_reg = SC_LOGIC_0;
    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "0001";
    start_once_reg = SC_LOGIC_0;
    start_control_reg = SC_LOGIC_0;
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "call_Loop_LB2D_buf_p_1_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, start_full_n, "(port)start_full_n");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, start_out, "(port)start_out");
    sc_trace(mVcdFile, start_write, "(port)start_write");
    sc_trace(mVcdFile, in_stream_V_value_V_dout, "(port)in_stream_V_value_V_dout");
    sc_trace(mVcdFile, in_stream_V_value_V_empty_n, "(port)in_stream_V_value_V_empty_n");
    sc_trace(mVcdFile, in_stream_V_value_V_read, "(port)in_stream_V_value_V_read");
    sc_trace(mVcdFile, slice_stream_V_value_V_din, "(port)slice_stream_V_value_V_din");
    sc_trace(mVcdFile, slice_stream_V_value_V_full_n, "(port)slice_stream_V_value_V_full_n");
    sc_trace(mVcdFile, slice_stream_V_value_V_write, "(port)slice_stream_V_value_V_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, real_start, "real_start");
    sc_trace(mVcdFile, real_start_status_reg, "real_start_status_reg");
    sc_trace(mVcdFile, internal_ap_ready, "internal_ap_ready");
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, start_once_reg, "start_once_reg");
    sc_trace(mVcdFile, start_control_reg, "start_control_reg");
    sc_trace(mVcdFile, in_stream_V_value_V_blk_n, "in_stream_V_value_V_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_flag00000000, "ap_block_pp0_stage0_flag00000000");
    sc_trace(mVcdFile, slice_stream_V_value_V_blk_n, "slice_stream_V_value_V_blk_n");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, tmp_s_reg_171, "tmp_s_reg_171");
    sc_trace(mVcdFile, col_reg_109, "col_reg_109");
    sc_trace(mVcdFile, tmp_fu_120_p2, "tmp_fu_120_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, row_1_fu_126_p2, "row_1_fu_126_p2");
    sc_trace(mVcdFile, row_1_reg_166, "row_1_reg_166");
    sc_trace(mVcdFile, tmp_s_fu_132_p2, "tmp_s_fu_132_p2");
    sc_trace(mVcdFile, tmp_1_fu_138_p2, "tmp_1_fu_138_p2");
    sc_trace(mVcdFile, tmp_1_reg_175, "tmp_1_reg_175");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter0, "ap_block_state3_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter1, "ap_block_state4_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter2, "ap_block_state5_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_pp0_stage0_flag00011001, "ap_block_pp0_stage0_flag00011001");
    sc_trace(mVcdFile, ap_reg_pp0_iter1_tmp_1_reg_175, "ap_reg_pp0_iter1_tmp_1_reg_175");
    sc_trace(mVcdFile, col_1_fu_144_p2, "col_1_fu_144_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, col_cast_fu_150_p1, "col_cast_fu_150_p1");
    sc_trace(mVcdFile, col_cast_reg_184, "col_cast_reg_184");
    sc_trace(mVcdFile, ap_reg_pp0_iter1_col_cast_reg_184, "ap_reg_pp0_iter1_col_cast_reg_184");
    sc_trace(mVcdFile, tmp_value_V_3_reg_194, "tmp_value_V_3_reg_194");
    sc_trace(mVcdFile, buffer_0_value_V_q0, "buffer_0_value_V_q0");
    sc_trace(mVcdFile, p_Val2_s_reg_200, "p_Val2_s_reg_200");
    sc_trace(mVcdFile, ap_block_pp0_stage0_flag00011011, "ap_block_pp0_stage0_flag00011011");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state3, "ap_condition_pp0_exit_iter0_state3");
    sc_trace(mVcdFile, buffer_0_value_V_address0, "buffer_0_value_V_address0");
    sc_trace(mVcdFile, buffer_0_value_V_ce0, "buffer_0_value_V_ce0");
    sc_trace(mVcdFile, buffer_0_value_V_address1, "buffer_0_value_V_address1");
    sc_trace(mVcdFile, buffer_0_value_V_ce1, "buffer_0_value_V_ce1");
    sc_trace(mVcdFile, buffer_0_value_V_we1, "buffer_0_value_V_we1");
    sc_trace(mVcdFile, row_reg_98, "row_reg_98");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, ap_block_pp0_stage0_flag00001001, "ap_block_pp0_stage0_flag00001001");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_block_pp0, "ap_block_pp0");
    sc_trace(mVcdFile, ap_enable_operation_40, "ap_enable_operation_40");
    sc_trace(mVcdFile, ap_enable_state5_pp0_iter2_stage0, "ap_enable_state5_pp0_iter2_stage0");
    sc_trace(mVcdFile, ap_predicate_op30_load_state3, "ap_predicate_op30_load_state3");
    sc_trace(mVcdFile, ap_enable_operation_30, "ap_enable_operation_30");
    sc_trace(mVcdFile, ap_enable_state3_pp0_iter0_stage0, "ap_enable_state3_pp0_iter0_stage0");
    sc_trace(mVcdFile, ap_enable_operation_32, "ap_enable_operation_32");
    sc_trace(mVcdFile, ap_enable_state4_pp0_iter1_stage0, "ap_enable_state4_pp0_iter1_stage0");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
}

call_Loop_LB2D_buf_p_1::~call_Loop_LB2D_buf_p_1() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete buffer_0_value_V_U;
}

void call_Loop_LB2D_buf_p_1::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(tmp_fu_120_p2.read(), ap_const_lv1_1))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011011.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state3.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, tmp_fu_120_p2.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011011.read(), ap_const_boolean_0)) {
            if (esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state3.read())) {
                ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state3.read() ^ ap_const_logic_1);
            } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
                ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
            }
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011011.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, tmp_fu_120_p2.read()))) {
            ap_enable_reg_pp0_iter2 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_1_fu_138_p2.read()))) {
        col_reg_109 = col_1_fu_144_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, tmp_fu_120_p2.read()))) {
        col_reg_109 = ap_const_lv11_0;
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        real_start_status_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(start_full_n.read(), ap_const_logic_1)) {
            real_start_status_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_0, start_full_n.read()) && 
                    esl_seteq<1,1,1>(ap_const_logic_1, internal_ap_ready.read()))) {
            real_start_status_reg = ap_const_logic_1;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        row_reg_98 = row_1_reg_166.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        row_reg_98 = ap_const_lv11_0;
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        start_control_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
             (esl_seteq<1,1,1>(ap_const_logic_1, internal_ap_ready.read()) || 
              esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read())))) {
            start_control_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, start_control_reg.read())) {
            start_control_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        start_once_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, real_start.read())) {
            start_once_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read())) {
            start_once_reg = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011001.read(), ap_const_boolean_0))) {
        ap_reg_pp0_iter1_col_cast_reg_184 = col_cast_reg_184.read();
        ap_reg_pp0_iter1_tmp_1_reg_175 = tmp_1_reg_175.read();
        tmp_1_reg_175 = tmp_1_fu_138_p2.read();
        tmp_value_V_3_reg_194 = in_stream_V_value_V_dout.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_1_fu_138_p2.read()))) {
        col_cast_reg_184 = col_cast_fu_150_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(tmp_s_reg_171.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011001.read(), ap_const_boolean_0))) {
        p_Val2_s_reg_200 = buffer_0_value_V_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        row_1_reg_166 = row_1_fu_126_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_fu_120_p2.read()))) {
        tmp_s_reg_171 = tmp_s_fu_132_p2.read();
    }
}

void call_Loop_LB2D_buf_p_1::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[2];
}

void call_Loop_LB2D_buf_p_1::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void call_Loop_LB2D_buf_p_1::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void call_Loop_LB2D_buf_p_1::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[3];
}

void call_Loop_LB2D_buf_p_1::thread_ap_block_pp0() {
    ap_block_pp0 = esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_pp0_stage0_flag00011011.read());
}

void call_Loop_LB2D_buf_p_1::thread_ap_block_pp0_stage0_flag00000000() {
    ap_block_pp0_stage0_flag00000000 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void call_Loop_LB2D_buf_p_1::thread_ap_block_pp0_stage0_flag00001001() {
    ap_block_pp0_stage0_flag00001001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, in_stream_V_value_V_empty_n.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
  esl_seteq<1,1,1>(tmp_s_reg_171.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, slice_stream_V_value_V_full_n.read())));
}

void call_Loop_LB2D_buf_p_1::thread_ap_block_pp0_stage0_flag00011001() {
    ap_block_pp0_stage0_flag00011001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, in_stream_V_value_V_empty_n.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
  esl_seteq<1,1,1>(tmp_s_reg_171.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, slice_stream_V_value_V_full_n.read())));
}

void call_Loop_LB2D_buf_p_1::thread_ap_block_pp0_stage0_flag00011011() {
    ap_block_pp0_stage0_flag00011011 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, in_stream_V_value_V_empty_n.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
  esl_seteq<1,1,1>(tmp_s_reg_171.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, slice_stream_V_value_V_full_n.read())));
}

void call_Loop_LB2D_buf_p_1::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void call_Loop_LB2D_buf_p_1::thread_ap_block_state3_pp0_stage0_iter0() {
    ap_block_state3_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void call_Loop_LB2D_buf_p_1::thread_ap_block_state4_pp0_stage0_iter1() {
    ap_block_state4_pp0_stage0_iter1 = esl_seteq<1,1,1>(ap_const_logic_0, in_stream_V_value_V_empty_n.read());
}

void call_Loop_LB2D_buf_p_1::thread_ap_block_state5_pp0_stage0_iter2() {
    ap_block_state5_pp0_stage0_iter2 = (esl_seteq<1,1,1>(tmp_s_reg_171.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, slice_stream_V_value_V_full_n.read()));
}

void call_Loop_LB2D_buf_p_1::thread_ap_condition_pp0_exit_iter0_state3() {
    if (esl_seteq<1,1,1>(tmp_1_fu_138_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state3 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state3 = ap_const_logic_0;
    }
}

void call_Loop_LB2D_buf_p_1::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(tmp_fu_120_p2.read(), ap_const_lv1_1))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void call_Loop_LB2D_buf_p_1::thread_ap_enable_operation_30() {
    ap_enable_operation_30 = esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op30_load_state3.read());
}

void call_Loop_LB2D_buf_p_1::thread_ap_enable_operation_32() {
    ap_enable_operation_32 = esl_seteq<1,1,1>(tmp_s_reg_171.read(), ap_const_lv1_0);
}

void call_Loop_LB2D_buf_p_1::thread_ap_enable_operation_40() {
    ap_enable_operation_40 = esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_pp0_iter1_tmp_1_reg_175.read());
}

void call_Loop_LB2D_buf_p_1::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void call_Loop_LB2D_buf_p_1::thread_ap_enable_state3_pp0_iter0_stage0() {
    ap_enable_state3_pp0_iter0_stage0 = (esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1));
}

void call_Loop_LB2D_buf_p_1::thread_ap_enable_state4_pp0_iter1_stage0() {
    ap_enable_state4_pp0_iter1_stage0 = (esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_1));
}

void call_Loop_LB2D_buf_p_1::thread_ap_enable_state5_pp0_iter2_stage0() {
    ap_enable_state5_pp0_iter2_stage0 = (esl_seteq<1,1,1>(ap_enable_reg_pp0_iter2.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_logic_1));
}

void call_Loop_LB2D_buf_p_1::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void call_Loop_LB2D_buf_p_1::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void call_Loop_LB2D_buf_p_1::thread_ap_predicate_op30_load_state3() {
    ap_predicate_op30_load_state3 = (esl_seteq<1,1,1>(tmp_s_reg_171.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_1_fu_138_p2.read()));
}

void call_Loop_LB2D_buf_p_1::thread_ap_ready() {
    ap_ready = internal_ap_ready.read();
}

void call_Loop_LB2D_buf_p_1::thread_buffer_0_value_V_address0() {
    buffer_0_value_V_address0 =  (sc_lv<11>) (col_cast_fu_150_p1.read());
}

void call_Loop_LB2D_buf_p_1::thread_buffer_0_value_V_address1() {
    buffer_0_value_V_address1 =  (sc_lv<11>) (ap_reg_pp0_iter1_col_cast_reg_184.read());
}

void call_Loop_LB2D_buf_p_1::thread_buffer_0_value_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        buffer_0_value_V_ce0 = ap_const_logic_1;
    } else {
        buffer_0_value_V_ce0 = ap_const_logic_0;
    }
}

void call_Loop_LB2D_buf_p_1::thread_buffer_0_value_V_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011001.read(), ap_const_boolean_0))) {
        buffer_0_value_V_ce1 = ap_const_logic_1;
    } else {
        buffer_0_value_V_ce1 = ap_const_logic_0;
    }
}

void call_Loop_LB2D_buf_p_1::thread_buffer_0_value_V_we1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_pp0_iter1_tmp_1_reg_175.read()))) {
        buffer_0_value_V_we1 = ap_const_logic_1;
    } else {
        buffer_0_value_V_we1 = ap_const_logic_0;
    }
}

void call_Loop_LB2D_buf_p_1::thread_col_1_fu_144_p2() {
    col_1_fu_144_p2 = (!col_reg_109.read().is_01() || !ap_const_lv11_1.is_01())? sc_lv<11>(): (sc_biguint<11>(col_reg_109.read()) + sc_biguint<11>(ap_const_lv11_1));
}

void call_Loop_LB2D_buf_p_1::thread_col_cast_fu_150_p1() {
    col_cast_fu_150_p1 = esl_zext<64,11>(col_reg_109.read());
}

void call_Loop_LB2D_buf_p_1::thread_in_stream_V_value_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00000000.read(), ap_const_boolean_0))) {
        in_stream_V_value_V_blk_n = in_stream_V_value_V_empty_n.read();
    } else {
        in_stream_V_value_V_blk_n = ap_const_logic_1;
    }
}

void call_Loop_LB2D_buf_p_1::thread_in_stream_V_value_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011001.read(), ap_const_boolean_0))) {
        in_stream_V_value_V_read = ap_const_logic_1;
    } else {
        in_stream_V_value_V_read = ap_const_logic_0;
    }
}

void call_Loop_LB2D_buf_p_1::thread_internal_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(tmp_fu_120_p2.read(), ap_const_lv1_1))) {
        internal_ap_ready = ap_const_logic_1;
    } else {
        internal_ap_ready = ap_const_logic_0;
    }
}

void call_Loop_LB2D_buf_p_1::thread_real_start() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, real_start_status_reg.read())) {
        real_start = ap_const_logic_0;
    } else {
        real_start = ap_start.read();
    }
}

void call_Loop_LB2D_buf_p_1::thread_row_1_fu_126_p2() {
    row_1_fu_126_p2 = (!row_reg_98.read().is_01() || !ap_const_lv11_1.is_01())? sc_lv<11>(): (sc_biguint<11>(row_reg_98.read()) + sc_biguint<11>(ap_const_lv11_1));
}

void call_Loop_LB2D_buf_p_1::thread_slice_stream_V_value_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00000000.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(tmp_s_reg_171.read(), ap_const_lv1_0))) {
        slice_stream_V_value_V_blk_n = slice_stream_V_value_V_full_n.read();
    } else {
        slice_stream_V_value_V_blk_n = ap_const_logic_1;
    }
}

void call_Loop_LB2D_buf_p_1::thread_slice_stream_V_value_V_din() {
    slice_stream_V_value_V_din = esl_concat<32,32>(tmp_value_V_3_reg_194.read(), p_Val2_s_reg_200.read());
}

void call_Loop_LB2D_buf_p_1::thread_slice_stream_V_value_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(tmp_s_reg_171.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011001.read(), ap_const_boolean_0))) {
        slice_stream_V_value_V_write = ap_const_logic_1;
    } else {
        slice_stream_V_value_V_write = ap_const_logic_0;
    }
}

void call_Loop_LB2D_buf_p_1::thread_start_out() {
    start_out = real_start.read();
}

void call_Loop_LB2D_buf_p_1::thread_start_write() {
    start_write = (ap_start.read() & start_control_reg.read());
}

void call_Loop_LB2D_buf_p_1::thread_tmp_1_fu_138_p2() {
    tmp_1_fu_138_p2 = (!col_reg_109.read().is_01() || !ap_const_lv11_77E.is_01())? sc_lv<1>(): sc_lv<1>(col_reg_109.read() == ap_const_lv11_77E);
}

void call_Loop_LB2D_buf_p_1::thread_tmp_fu_120_p2() {
    tmp_fu_120_p2 = (!row_reg_98.read().is_01() || !ap_const_lv11_436.is_01())? sc_lv<1>(): sc_lv<1>(row_reg_98.read() == ap_const_lv11_436);
}

void call_Loop_LB2D_buf_p_1::thread_tmp_s_fu_132_p2() {
    tmp_s_fu_132_p2 = (!row_reg_98.read().is_01() || !ap_const_lv11_0.is_01())? sc_lv<1>(): sc_lv<1>(row_reg_98.read() == ap_const_lv11_0);
}

void call_Loop_LB2D_buf_p_1::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(tmp_fu_120_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011011.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011011.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(tmp_1_fu_138_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011011.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_flag00011011.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(tmp_1_fu_138_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        default : 
            ap_NS_fsm = "XXXX";
            break;
    }
}

}

